In [1]:
import numpy as np
import pandas as pd
import requests
import json

In [2]:
import matplotlib.pyplot as plt

In [4]:
bank = pd.read_csv('~/Desktop/Dataset/BankChurners.csv')

In [5]:
bank.head()

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0  768805383  Existing Customer            45      M                3   
1  818770008  Existing Customer            49      F                5   
2  713982108  Existing Customer            51      M                3   
3  769911858  Existing Customer            40      F                4   
4  709106358  Existing Customer            40      M                3   

  Education_Level Marital_Status Income_Category Card_Category  \
0     High School        Married     $60K - $80K          Blue   
1        Graduate         Single  Less than $40K          Blue   
2        Graduate        Married    $80K - $120K          Blue   
3     High School        Unknown  Less than $40K          Blue   
4      Uneducated        Married     $60K - $80K          Blue   

   Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
0              39  ...       12691.0                  777          11914.0   
1              44  ...        8256.0                  864           7392.0   
2              36  ...        3418.0                    0           3418.0   
3              34  ...        3313.0                 2517            796.0   
4              21  ...        4716.0                    0           4716.0   

   Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  \
0                 1.335             1144              42                1.625   
1                 1.541             1291              33                3.714   
2                 2.594             1887              20                2.333   
3                 1.405             1171              20                2.333   
4                 2.175              816              28                2.500   

   Avg_Utilization_Ratio  \
0                  0.061   
1                  0.105   
2                  0.000   
3                  0.760   
4                  0.000   

   Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  \
0                                           0.000093                                                                                    
1                                           0.000057                                                                                    
2                                           0.000021                                                                                    
3                                           0.000134                                                                                    
4                                           0.000022                                                                                    

   Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  
0                                            0.99991                                                                                   
1                                            0.99994                                                                                   
2                                            0.99998                                                                                   
3                                            0.99987                                                                                   
4                                            0.99998                                                                                   

[5 rows x 23 columns]

In [34]:
bank.iloc[1:3]

Attrition_Flag  Customer_Age Gender  Dependent_count  \
CLIENTNUM                                                            
818770008  Existing Customer            49      F                5   
713982108  Existing Customer            51      M                3   

          Education_Level Marital_Status Income_Category Card_Category  \
CLIENTNUM                                                                
818770008        Graduate         Single  Less than $40K          Blue   
713982108        Graduate        Married    $80K - $120K          Blue   

           Months_on_book  Total_Relationship_Count  ...  Credit_Limit  \
CLIENTNUM                                            ...                 
818770008              44                         6  ...        8256.0   
713982108              36                         4  ...        3418.0   

           Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
CLIENTNUM                                                               
818770008                  864           7392.0                 1.541   
713982108                    0           3418.0                 2.594   

           Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  \
CLIENTNUM                                                         
818770008             1291              33                3.714   
713982108             1887              20                2.333   

           Avg_Utilization_Ratio  \
CLIENTNUM                          
818770008                  0.105   
713982108                  0.000   

           Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  \
CLIENTNUM                                                                                                                                       
818770008                                           0.000057                                                                                    
713982108                                           0.000021                                                                                    

           Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  
CLIENTNUM                                                                                                                                      
818770008                                            0.99994                                                                                   
713982108                                            0.99998                                                                                   

[2 rows x 22 columns]

In [52]:
bank.loc[768805383,'Gender']

'M'

In [6]:
matrix_a = np.array([[1,2,3],[4,5,6]])

In [7]:
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
matrix_b = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_b

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [9]:
matrix_b[::2,::3]

array([[1, 2],
       [4, 8]])

In [10]:
matrix_b[matrix_b[:,:] >= 2]

array([2, 3, 6, 6, 7, 4, 4, 5, 3, 8])

SQUEEZE AND DIMENSIONS

In [11]:
array_full_like = np.full_like(matrix_b, fill_value=23)
array_full_like

array([[23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23]])

In [12]:
a_range = np.arange(20, step=2, dtype=np.int8)
a_range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int8)

<h2>Random Generators</h2>

In [15]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [128]:
array_rg = gen(pcg(seed=20))
array_rg.choice([1,255,54,54,545],size=(2,2))

array([[545, 255],
       [255,  54]])

In [129]:
array_rg = gen(pcg(seed=20))
array_rg.random(size=(2,2))

array([[0.28007596, 0.46114671],
       [0.12171969, 0.52260835]])

In [131]:
array_rg = gen(pcg(seed=20))
array_rg.integers(low=25,high=36,size=(2,2))

array([[34, 28],
       [27, 30]])

In [132]:
# array normal random generator gives decimal numbers
array_rg = gen(pcg(seed=20))
array_rg.normal(size=(2,2))

array([[-0.35966846,  1.2036751 ],
       [ 1.39686812,  0.31723593]])

In [137]:
array_rg = gen(pcg())
array_rg.normal(size=(2,2))

array([[ 0.11737745, -0.46477147],
       [ 2.95516209,  1.52261519]])

<h2>Probability Distributions<h2/>

In [16]:
array_rg = gen(pcg(seed=35))
array_rg.poisson(lam = 5, size=(5,5))

array([[ 5,  8,  1,  4,  6],
       [ 3,  5,  3,  6,  3],
       [ 4,  8,  5,  2,  5],
       [ 6,  6, 11,  2,  3],
       [ 4,  5,  6,  5,  2]])

In [17]:
# Random Generator Binomial
array_rg = gen(pcg(seed=35))
array_rg.binomial(n=100, p=0.8, size=(5,5))

array([[82, 81, 74, 73, 85],
       [91, 81, 75, 77, 75],
       [76, 84, 72, 82, 91],
       [87, 87, 79, 79, 85],
       [78, 84, 81, 82, 76]])

In [20]:
array_rg = gen(pcg(seed=35))
array_rg.logistic(loc=5, scale=1.5, size=(5,5))

array([[ 3.99133235,  4.75039899,  8.99940798,  9.31930961,  1.64980249],
       [-5.53169172,  4.71890791,  8.44004622,  7.18044393,  8.37011094],
       [ 7.20388675,  2.54319506, 10.76174722,  4.12333116, -5.32170661],
       [ 0.36889744, -0.27340439,  5.4923123 ,  5.45638925,  1.73317821],
       [ 6.12070091,  2.51109678,  4.45218448,  3.96387788,  7.65583326]])

<h2>Statistics with Numpy</h2>

In [154]:
matrix_b

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [22]:
np.mean(matrix_b, axis=0)

array([2.66666667, 4.        , 3.33333333, 5.66666667, 1.33333333])

In [165]:
matrix_b

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [23]:
np.min(matrix_b[:,3])

2

In [25]:
np.amin(matrix_b[1,:])

3

In [163]:
np.max(matrix_b)

8

In [168]:
np.minimum(matrix_b[1],matrix_b[2])

array([3, 5, 3, 7, 0])

In [180]:
a0 =np.maximum.reduce(matrix_b)
a1 =np.max(matrix_b, axis=0)
a0, a1

(array([4, 6, 6, 8, 4]), array([4, 6, 6, 8, 4]))

In [181]:
np.sort(matrix_b, axis=None)

array([0, 0, 1, 1, 1, 2, 3, 3, 4, 4, 5, 6, 6, 7, 8])

In [185]:
np.percentile(matrix_b, 70, method = 'nearest')

5

In [32]:
np.quantile(matrix_b,q=0.4).round(2)

2.6